server.port=9210

spring.application.name=libraryapp


# ===== Datasource =====
spring.datasource.url=jdbc:postgresql://localhost:5432/libraryapp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== Connection pool (HikariCP) =====
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update

# ===== Logging =====
logging.level.root=INFO
logging.level.com.jhorgi.libraryapp=DEBUG
logging.level.org.hibernate.SQL=DEBUG
